<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Perspective\MultisearchIo\Model\MultisearchViewModel;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var MultisearchViewModel $multisearchViewModel */
if (empty($viewModels)) {
    $multisearchViewModel = \Magento\Framework\App\ObjectManager::getInstance()->get(MultisearchViewModel::class);
} else {
    $multisearchViewModel = $viewModels->require(MultisearchViewModel::class);
}
?>
<script>
    var MULTISEARCH_TRACKER_ID = '<?=  /* @noEscape */ ($multisearchViewModel->getMultisearchTrackerId()) ?>';
</script>
